package mapreduce

import (
	"encoding/json"
	"hash/fnv"
	"io/ioutil"
	"os"
)

func doMap(
	jobName string, // the name of the MapReduce job
	mapTask int, // which map task this is
	inFile string,
	nReduce int, // the number of reduce task that will be run ("R" in the paper)
	mapF func(filename string, contents string) []KeyValue,
) {
	// There is one intermediate file per reduce task. The file name
	// includes both the map task number and the reduce task number. Use
	// the filename generated by reduceName(jobName, mapTask, r)
	// as the intermediate file for reduce task r. Call ihash() (see
	// below) on each key, mod nReduce, to pick r for a key/value pair.
	//
	// mapF() is the map function provided by the application. The first
	// argument should be the input file name, though the map function
	// typically ignores it. The second argument should be the entire
	// input file contents. mapF() returns a slice containing the
	// key/value pairs for reduce; see common.go for the definition of
	// KeyValue.
	//

	// Read File content
	content, err := ioutil.ReadFile(inFile)
	if err != nil {
		panic(err)
	}
	// Apply the user defined function to the content
	keysValues := mapF(inFile, string(content[:]))

	// Partition the intermediate output into files
	for _, kv := range keysValues {
		filename := reduceName(jobName, mapTask, ihash(kv.Key)%nReduce)

		//Create a file if don't exist in append mode
		fd, err := os.OpenFile(filename, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0755)
		if err != nil {
			panic(err)
		}

		//Jsonfy the structure
		encodedKV, err := json.Marshal(&kv)
		if err != nil {
			panic(err)
		}

		fd.Write(encodedKV)
		fd.Close()
	}
}

func ihash(s string) int {
	h := fnv.New32a()
	h.Write([]byte(s))
	return int(h.Sum32() & 0x7fffffff)
}
